name: Question
description: Ask about something here.
labels: [question]
body:
  - type: textarea
    attributes:
      label: What is your question?
      placeholder: "Please note! If you're just giving comments for NF, please go to NF's repository to raise an issue"
    validations:
      required: true
